-- CADERNO DE CAMPO
-- Configuração inicial do Supabase
--
-- Execute este arquivo no SQL Editor do projeto novo.
-- O bucket "activity-photos" deve existir como bucket público ou privado
-- com as políticas abaixo. O aplicativo usa download autenticado via Storage API.

create table if not exists public.sync_data (
  id bigint generated by default as identity primary key,
  uuid uuid not null unique,
  table_name text not null,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted boolean not null default false
);

create index if not exists sync_data_table_name_idx
  on public.sync_data(table_name);

create index if not exists sync_data_updated_at_idx
  on public.sync_data(updated_at);

alter table public.sync_data enable row level security;

drop policy if exists "sync_data_anon_all" on public.sync_data;

create policy "sync_data_anon_all"
  on public.sync_data
  for all
  to anon
  using (true)
  with check (true);

-- ============================================================
-- STORAGE
-- ============================================================

drop policy if exists "activity_photos_insert" on storage.objects;
drop policy if exists "activity_photos_select" on storage.objects;
drop policy if exists "activity_photos_update" on storage.objects;
drop policy if exists "activity_photos_delete" on storage.objects;

create policy "activity_photos_insert"
  on storage.objects
  for insert
  to anon
  with check (bucket_id = 'activity-photos');

create policy "activity_photos_select"
  on storage.objects
  for select
  to anon
  using (bucket_id = 'activity-photos');

create policy "activity_photos_update"
  on storage.objects
  for update
  to anon
  using (bucket_id = 'activity-photos')
  with check (bucket_id = 'activity-photos');

create policy "activity_photos_delete"
  on storage.objects
  for delete
  to anon
  using (bucket_id = 'activity-photos');
